# Generated by Django 4.2.1 on 2023-06-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authentication",
            name="force_reset",
            field=models.BooleanField(default=False),
        ),
    ]
