# Generated by Django 4.2.1 on 2023-05-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_product_brand_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="related_products",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
