# Generated by Django 4.2.1 on 2023-06-04 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b3c92768-306c-4be3-b388-9e9cd68f0445"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
