# Generated by Django 4.2.1 on 2023-06-02 08:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("customer", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("update_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("54c6d43d-3591-443a-a324-a6eff3802eea"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel_id", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "currency",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "locale",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="customer.customer",
                    ),
                ),
                ("discounts", models.ManyToManyField(null=True, to="order.discount")),
                ("line_item", models.ManyToManyField(null=True, to="product.product")),
            ],
            options={
                "verbose_name": "cart",
                "verbose_name_plural": "carts",
                "db_table": "cart",
            },
        ),
    ]
