# Generated by Django 4.2.1 on 2023-05-31 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("created_at", models.DateTimeField(auto_now=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("7bfa9856-5fed-4422-b727-9ad310abee3c"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("line_item", models.JSONField(default=dict)),
                ("custom_items", models.JSONField(default=dict)),
                ("gift_certificates", models.JSONField(default=dict)),
                ("customer_id", models.IntegerField(default=0)),
                ("channel_id", models.IntegerField(default=0)),
                ("currency", models.JSONField(default=dict)),
                ("locale", models.CharField(default="", max_length=200)),
                ("email", models.CharField(default="", max_length=200)),
                ("tax_included", models.BooleanField(default=False)),
                ("discount_amount", models.IntegerField(default=0)),
                ("cart_amount", models.IntegerField(default=0)),
                ("discounts", models.JSONField(default=dict)),
                ("coupons", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "cart",
                "verbose_name_plural": "carts",
                "db_table": "cart",
            },
        ),
    ]
