# Generated by Django 4.2.1 on 2023-06-02 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7257d7cf-565a-484d-b8f9-9c240632a8a7"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
