# Generated by Django 4.2.1 on 2023-06-01 07:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_alter_customer__authentication"),
        ("product", "0011_alter_product_categories_and_more"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="customer_id",
        ),
        migrations.AddField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(to="product.product"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b7a5de95-b060-4b55-89da-9b072bc8bfca"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
