# Generated by Django 4.2.1 on 2023-06-04 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authentication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("update_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("password", models.CharField(default="", max_length=200)),
                (
                    "password_confirmation",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("force_reset", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "authentication",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("update_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("first_name", models.CharField(default="", max_length=200)),
                ("last_name", models.CharField(default="", max_length=200)),
                ("phone", models.CharField(default="", max_length=200)),
                ("email", models.CharField(default="", max_length=200)),
                (
                    "company",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("store_credit", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "registration_ip_address",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "customer_group_id",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "notes",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "authentication",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="customer.authentication",
                    ),
                ),
            ],
            options={
                "verbose_name": "customer",
                "verbose_name_plural": "customers",
                "db_table": "customer",
            },
        ),
    ]
