# Generated by Django 4.2.1 on 2023-06-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="line_item",
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(null=True, to="order.line_items"),
        ),
    ]
