# Generated by Django 4.2.1 on 2023-06-04 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("update_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "brand",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "brand",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("update_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "category",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("update_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "tax_name",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("tax", models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                "db_table": "tax",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("update_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("name", models.CharField(default="", max_length=200)),
                ("type", models.CharField(default="", max_length=20)),
                (
                    "sku",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=1000, null=True
                    ),
                ),
                ("weight", models.IntegerField(default=0)),
                ("width", models.IntegerField(blank=True, default=0, null=True)),
                ("depth", models.IntegerField(blank=True, default=0, null=True)),
                ("height", models.IntegerField(blank=True, default=0, null=True)),
                ("price", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "search_keywords",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("images", models.JSONField(blank=True, default=dict, null=True)),
                ("videos", models.JSONField(blank=True, default=dict, null=True)),
                ("total_sold", models.IntegerField(blank=True, default=0, null=True)),
                ("view_count", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.category",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.tax",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "db_table": "product",
            },
        ),
    ]
