# Generated by Django 4.2.1 on 2023-05-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                ("billing_address", models.JSONField(default=dict)),
                ("products", models.JSONField(blank=True, default=dict, null=True)),
                ("consignments", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "shipping_addresses",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("status_id", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "base_handling_cost",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "base_shipping_cost",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "base_wrapping_cost",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("channel_id", models.IntegerField(blank=True, default=0, null=True)),
                ("customer_id", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "customer_message",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "default_currency_code",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "discount_amount",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "geoip_country",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "customer_locales",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "ip_address",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("is_deleted", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "items_shipped",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("items_total", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "order_is_digital",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "payment_provider_id",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "subtotal_ex_tax",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "subtotal_inc_tax",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "db_table": "order",
            },
        ),
    ]
