# Generated by Django 4.2.1 on 2023-06-02 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Billing_address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("update_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "company",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "street",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "state",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "country",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "phone",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "email",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "billing_address",
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("update_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("discount", models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                "db_table": "discount",
            },
        ),
        migrations.CreateModel(
            name="Line_items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("update_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "line_items",
            },
        ),
        migrations.CreateModel(
            name="Shipping_address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("update_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "company",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "street",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "state",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "country",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "phone",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "email",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "shipping_method",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "shipping_address",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("update_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("status_id", models.IntegerField(blank=True, default=1, null=True)),
                ("order_is_digital", models.BooleanField(default=False)),
                ("channel_id", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "customer_message",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "geoip_country",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "customer_locales",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "ip_address",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "base_handling_cost",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "base_shipping_cost",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "base_wrapping_cost",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "default_currency_code",
                    models.CharField(
                        blank=True, default="CNY", max_length=200, null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "payment_provider_id",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "billing_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="order.billing_address",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="customer.customer",
                    ),
                ),
                ("discounts", models.ManyToManyField(null=True, to="order.discount")),
                (
                    "line_items",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="order.line_items",
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="order.shipping_address",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "db_table": "order",
            },
        ),
    ]
