# Generated by Django 4.2.1 on 2023-05-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_shipping_addresses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="consignments",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="order",
            name="default_currency_code",
            field=models.CharField(blank=True, default="CNY", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_is_digital",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.JSONField(default=dict),
        ),
    ]
